### ISSUE TITLE
cannot install angularjs.Typescript.DefinitelyTyped

### ISSUE THREAD

**Issue by 5angel** [DefinitelyTyped/NugetAutomation#15]
Response status code does not indicate success: 400 (One of the request inputs is out of range.).

**Comment by staxmanade** [comment]
is this related? https://github.com/borisyankov/DefinitelyTyped/issues/4241

**Comment by 5angel** [comment]
@staxmanade yup, that's it

**Comment by staxmanade** [comment]
Closing for now, let me know if there is anything more you have to add...

**Comment by kelong** [comment]
The same error with angular-ui.TypeScript.DefinitelyTyped.

**Comment by basarat** [comment]
@kelong have you tried the update : http://blog.nuget.org/20150226/nuget-3.0-beta2.html

**Comment by kelong** [comment]
@basarat Yes, it is not nuget related problem. Only those 2 packages can't install in cordova project.

**Comment by basarat** [comment]
@kelong And you are getting the same error response : 400?

**Comment by kelong** [comment]
Yes

Rgrds,
Maciej Lelito




On Sun, May 31, 2015 at 2:32 PM -0700, "Basarat Ali Syed" <notifications@github.com> wrote:












@kelong And you are getting the same error response : 400?

**Comment by basarat** [comment]
But it works in a new non Cordova project?

**Comment by kelong** [comment]
It doesn't matter. I created new blank project. I see that new version angularjs.TypeScript.DefinitelyTyped 3.9.2 came out, will test this out.

**Comment by kelong** [comment]
I have nuget 3.0.60410.213 installed for VS2015 RC. Nuget package manager don't even see 3.9.2 version of angularjs.TypeScript.DefinitelyTyped. When I try manually enter version:
install-package angularjs.TypeScript.DefinitelyTyped -Version 3.9.2
still the same error:
Response status code does not indicate success: 400 (One of the request inputs is out of range.).

**Comment by basarat** [comment]
I am on Visual Studio 2013 Update 4 and it works fine: 

![image](https://cloud.githubusercontent.com/assets/874898/7925832/eba8655a-090c-11e5-9cd5-77773fe9b960.png)

And since the version is available on nuget : https://www.nuget.org/packages/angularjs.TypeScript.DefinitelyTyped/ I'd prefer if you reported it here : https://nuget.codeplex.com/WorkItem/Create?ProjectName=nuget < I know a horrible url to give someone but last I checked this was the way to go :rose:

**Comment by kelong** [comment]
Ok, thanks.

**Comment by basarat** [comment]
Thanks. For reference of everyone else the issue now lives here : https://nuget.codeplex.com/workitem/8333

**Comment by jbridge** [comment]
same problem, any solution?

**Comment by kelong** [comment]
Yes, it works on vs2013.
