### ISSUE TITLE
Nuget version change without source modification

### ISSUE THREAD

**Issue by SamuelGuine** [DefinitelyTyped/NugetAutomation#16]
Hi,

The nuget package version change many time by day for some package except they are no change in source.

Example : bootstrap
See History : [https://www.nuget.org/packages/bootstrap.TypeScript.DefinitelyTyped/](https://www.nuget.org/packages/bootstrap.TypeScript.DefinitelyTyped/)

Something wrong with automation ?

Best regards,

**Comment by staxmanade** [comment]
Ya, should be resolved now. The build was not completing due to a project-wide change causing all packages to be republished and the build not completing. Every two hours was restarting... It should be working now

**Comment by staxmanade** [comment]
@SamuelGuine see issue #17 with a good visual of the NuGet disruption this project had :stuck_out_tongue:

**Comment by SamuelGuine** [comment]
Sure, the charts speak for themselves :smiley:
