### ISSUE TITLE
Question How to use React defined interfaces

### ISSUE THREAD

**Issue by NoHomey** [DefinitelyTyped/NugetAutomation#18]
Is there a way to use interface types like KeyboardEvent or Types like React.KeyboardEventHandler outside of .d.ts file?

I've seen them used in material-ui.d.ts

```typescript
onKeyDown?: React.KeyboardEventHandler;
```

But I can't find a way to use them in mine React application.

If there is no way, is this issue discussed?

I mean is it thought about making them public available under Types or something like that just like DOM is for an example I know there is no such thing in React but in Typescript there is for sure need of it.

**Comment by staxmanade** [comment]
This repo is setup for the NugetAutomation publishing tool. Probably better to ask in another medium like: https://gitter.im/DefinitelyTyped/DefinitelyTyped

Just a quick thought - try accessing it by using:

```
var x: __React.KeyboardEventHandler;
```

If this doesn't work, take the question over to gitter and hopefully someone can help.
